services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    depends_on:
      - db
    command: ["sh", "./docker/entrypoint.sh"]
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: teste_receitas_rg_sistemas
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  adminer:
    image: adminer
    container_name: adminer_db_viewer
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - laravel

  vite:
    image: node:20
    container_name: vite_dev_server
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
    depends_on:
      - app
    networks:
      - laravel

  cypress:
    image: cypress/included:12.17.4
    container_name: cypress_tests
    working_dir: /e2e
    volumes:
      - .:/e2e
    depends_on:
      - app
    command: cypress run
    networks:
      - laravel

volumes:
  dbdata:


networks:
  laravel:
    driver: bridge
